### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: './features/IEMOCAP_ST.pkl

### ISSUE THREAD

**Issue by Coding511** [xiaomi1024/code_SAMS#1]
could you help : where is the features file? and if you have not included how to extract them? Without this file how train.py can work?

**Comment by Michell-H** [comment]
You can get the download link through the download.txt

**Comment by Coding511** [comment]
@Michell-H Tried that already, But that link is not working, Could you please upload features here, otherwise its hard to replicate the results and authentic it.

**Comment by xiaomi1024** [comment]
@Coding511 I have uploaded the files to Google Drive again，and you can try to download them though the link [https://drive.google.com/drive/folders/1Pak5wrqSzshX_hPokY8BYYIO6jnj9Zgl?usp=sharing].
